### ISSUE TITLE
Undefined index: max

### ISSUE THREAD

**Issue by jmawebtech** [jmawebtech/OpenCart-QuickBooks-JMA#1]
Hi,

http://www.X.co.uk/trackdays/index.php?route=feed/connex_qb&/index.php?route=feed/api&func=getOrders&endDate=2017-02-14 11:59:59&beginDate=2017-02-13 00:00:00&email=X&password=X&page=0&limit=150

<b>Notice</b>: Undefined index: max in <b>/home/sites/javelintrackdays.co.uk/public_html/trackdays/catalog/controller/feed/connex_qb.php</b>

**Comment by beechyrb** [comment]
Fixed
